Repository qor/sorting, pull requests merged in 2020-12, with the labels that each got.

#11 Add sorting mask cover
  views/themes/sorting/assets/javascripts/sorting.js
  views/themes/sorting/assets/javascripts/sorting/sorting.js
Labels: size/XS

#13 Update reload page after sorting response error
  views/themes/sorting/assets/javascripts/sorting.js
  views/themes/sorting/assets/javascripts/sorting/sorting.js
Labels: size/XS

#15 Update sorting mask effect
  views/themes/sorting/assets/javascripts/sorting.js
  views/themes/sorting/assets/javascripts/sorting/sorting.js
Labels: size/S

#14 remove RowsAffected, just set pos num
  sorting.go
  sorting_test.go
Labels: size/M
